### ISSUE TITLE
Release 1.13.0

### ISSUE THREAD

**Issue by abhinav** [thriftrw/thriftrw-go#372]
This issue is tracking the release of v1.13.0.

# Required

- [x] `go.label` support for enums (PR: #363)
- [x] Fast logging with Zap (PR: #366)
- [x] Opt-out of Zap code generation (PR: #369)
- [x] Fix linting (PR: #374)

# Nice to have

- [x] thriftrw-list-deps command (PR: #354)
- [x] Opt-out specific struct fields from being logged with an annotation
      (PR: #373)
- [x] `go.label` support for struct fields (Issue: #370, PR: #377)
- [x] Retain all Zap marshaling errors (Issue: #367, PR: #378)
- [x] TextMarshaler should round trip (Issue: #368)
- [x] Make Equals nil safe (Issue: #345, PR: #379)
- [x] Check field ID bounds (Issue: #72, PR: #380)

**Comment by abhinav** [comment]
Released.
